# Generated by Django 4.2.7 on 2023-11-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
