# Generated by Django 4.2.7 on 2023-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_post", "0002_alter_post_author"),
        ("apps_user", "0002_user_avatar_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="posts_liked",
            field=models.ManyToManyField(related_name="liked_by", to="apps_post.post"),
        ),
    ]
