# Generated by Django 4.2.7 on 2023-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_comment", "0002_alter_comment_comment_alter_comment_post"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("post__isnull", True),
                        ("comment__isnull", True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("post__isnull", True), ("comment__isnull", True), _negated=True
                    ),
                ),
                name="check_post_and_comment",
            ),
        ),
    ]
