# Generated by Django 4.2.7 on 2023-11-22 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_comment", "0003_comment_check_post_and_comment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="check_post_and_comment",
        ),
    ]
