# Generated by Django 4.2.7 on 2023-11-22 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_comment", "0004_remove_comment_check_post_and_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
    ]
